from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()
spark

from datetime import datetime
from dateutil.relativedelta import relativedelta

def log():
    return datetime.now().strftime('%Y-%m-%d %H:%M:%S') + ' >>>'

dt_proc = datetime.now().strftime('%Y%m%d%H%M%S')
current_date = datetime.now().strftime('%Y%m%d')

# Referência escolhida para o book
dt_proc_book = datetime.strptime('2024-02-01','%Y-%m-%d')

# Vamos olhar para os últimos 12 meses relativo à 2024-02-01
dt_ini_proc_book = dt_proc_book - relativedelta(months=12)

dt_proc_book = dt_proc_book.strftime('%Y%m')
dt_ini_proc_book = dt_ini_proc_book.strftime('%Y%m')

print(f'Data de referência do book >>> {dt_proc_book}')
print(f'Data de início do book >>> {dt_ini_proc_book}')

dt_proc_book_str = datetime.strptime('2024-02-01','%Y-%m-%d').strftime('%Y-%m-%d')
dt_proc_book_str

# Leitura dos dados Fatura
tb_fatura = spark.read.parquet("s3://lake-project-/0002_trusted/tb_0001_fatura")
tb_fatura_00 = tb_fatura.where(f'ref >= {dt_ini_proc_book} and ref <= {dt_proc_book}')
tb_fatura_00.createOrReplaceTempView('tb_fatura_00')

print('Verificando se o filtro foi aplicado em tb_faturas.')
spark.sql("SELECT MAX(ref), MIN(ref) FROM tb_fatura_00").show()

# Verificando duplicação de dados
spark.sql("""
      SELECT
            id_fatura,
            id_cliente,
            count(*)
      FROM
            tb_fatura_00
      GROUP BY
            id_fatura,
            id_cliente
      ORDER BY
            id_cliente DESC
""").show()
print('Se count() > 1, dados duplicados. Se count() = 1, dados únicos.')

# Leitura dos dados de Pagamentos
tb_pagamentos = spark.read.parquet("s3://lake-project-/0002_trusted/tb_0002_pagamentos")
tb_pagamentos_00 = tb_pagamentos.where(f'ref >= {dt_ini_proc_book} and ref <= {dt_proc_book}')
tb_pagamentos_00.createOrReplaceTempView('tb_pagamentos_00')

print('Verificando se o filtro foi aplicado em tb_pagamentos.')
spark.sql("SELECT MAX(ref), MIN(ref) FROM tb_pagamentos_00").show()

# Verificando duplicação de dados
spark.sql("""
      SELECT
            id_fatura,
            id_cliente,
            count(*)
      FROM
            tb_pagamentos_00
      GROUP BY
            id_fatura,
            id_cliente
      ORDER BY
            id_cliente DESC
""").show()
print('Se count() > 1, dados duplicados. Se count() = 1, dados únicos.')

"""## Stage layer"""

tb_fatura_00.columns

tb_pagamentos_00.columns

# Join de faturas e pagamentos
df_join = spark.sql("""
      SELECT
          a.id_cliente,
          a.id_fatura,
          a.dt_emissao,
          a.dt_vencimento,
          a.vlr_fatura,
          a.vlr_pagto_min,
          b.id_pagamento,
          b.dt_pagamento,
          b.vlr_pagamento
      FROM
          tb_fatura_00 a
      LEFT JOIN
          tb_pagamentos_00 b
      ON
          a.id_cliente = b.id_cliente and a.id_fatura = b.id_fatura
      ORDER BY
          a.id_cliente,
          a.id_fatura
""")
df_join.show()
df_join.createOrReplaceTempView('df_join')

# Criando uma classificação para o pagamento
tb_classificacao_pagamento = spark.sql("""
    SELECT
        *,
        CASE
            WHEN dt_pagamento is NULL THEN 'SEM_PAGAMENTO'
            WHEN dt_pagamento = dt_vencimento THEN 'PAGAMENTO_NO_PRAZO'
            WHEN dt_pagamento < dt_vencimento THEN 'PAGAMENTO_ANTECIPADO'
            ELSE 'PAGAMENTO_EM_ATRASO'
        END AS fbc_classif_pagto,
        CASE
            WHEN vlr_pagamento = vlr_fatura THEN 'VALOR_TOTAL'
            WHEN vlr_pagamento < vlr_fatura THEN 'VALOR_PARCIAL'
            ELSE 'SEM_VALOR'
        END AS fbc_classif_vlr_pagto
    FROM
        df_join
""")
tb_classificacao_pagamento.createOrReplaceTempView('tb_classificacao_pagamento')

print('Amostra tb_classificacao_pagamento:')
tb_classificacao_pagamento.show(5)

# Criando uma classificação para o valor do pagamento
tb_classificacao_valor_pagamento = spark.sql("""
        SELECT
              *,
              CASE
                  WHEN fbc_classif_vlr_pagto = 'VALOR_TOTAL' THEN 100
                  WHEN fbc_classif_vlr_pagto = 'VALOR_PARCIAL' THEN ROUND((vlr_pagamento*100)/vlr_fatura,0)
                  ELSE 0
              END AS fvl_perc_vlr_fatura
        FROM
              tb_classificacao_pagamento
""")
tb_classificacao_valor_pagamento.createOrReplaceTempView('tb_classificacao_valor_pagamento')

print('Amostra tb_classificacao_valor_pagamento:')
tb_classificacao_valor_pagamento.show(5)

# Tabela de dias em atraso
tb_dias_atraso = spark.sql(f"""
    SELECT
        *,
        CASE
            WHEN fbc_classif_pagto = 'SEM_PAGAMENTO' THEN datediff("{dt_proc_book_str}", dt_vencimento)
            WHEN fbc_classif_pagto = 'PAGAMENTO_EM_ATRASO' THEN datediff(dt_pagamento, dt_vencimento)
            WHEN fbc_classif_pagto = 'PAGAMENTO_NO_PRAZO' THEN 0
            ELSE -1
        END AS fvl_numero_dias_atraso
    FROM
        tb_classificacao_valor_pagamento
""")
tb_dias_atraso.createOrReplaceTempView('tb_dias_atraso')

print('Amostra tb_dias_atraso:')
tb_dias_atraso.show()

print('Colunas tb_dias_atraso:')
tb_dias_atraso.columns

# Criando uma tabela Stage
stage = spark.sql(f"""
      SELECT
          id_cliente,
          SUBSTRING(REPLACE("{dt_proc_book_str}",'-',''),1,6) AS ref,
          "{dt_proc}" AS dt_proc,
          fbc_classif_pagto,
          fbc_classif_vlr_pagto,
          dt_emissao,
          vlr_fatura AS fvl_vlr_fatura,
          vlr_pagamento AS fvl_vlr_pagto,
          vlr_pagto_min AS fvl_vlr_pagto_min,
          fvl_perc_vlr_fatura,
          fvl_numero_dias_atraso,
          1 AS fvl_qtd_transacao
      FROM
          tb_dias_atraso
""")
stage.createOrReplaceTempView('stage')

print('Amostra da tabela stage:')
stage.show(5)

print('Verificando os limites de dt_emissao da Stage')
spark.sql("SELECT MAX(dt_emissao), MIN(dt_emissao) FROM stage").show()

stage.write.partitionBy('ref').parquet("s3://lake-project-/0003_refined/stage/stage_fatura/", mode='append')

janelas_tempo = spark.sql(f"""
    SELECT
        *,
        (CASE WHEN MONTHS_BETWEEN("{dt_proc_book_str}", dt_emissao) <= 1 THEN 1 ELSE 0 END) flg_u1m,
        (CASE WHEN MONTHS_BETWEEN("{dt_proc_book_str}", dt_emissao) <= 3 THEN 1 ELSE 0 END) flg_u3m,
        (CASE WHEN MONTHS_BETWEEN("{dt_proc_book_str}", dt_emissao) <= 6 THEN 1 ELSE 0 END) flg_u6m,
        (CASE WHEN MONTHS_BETWEEN("{dt_proc_book_str}", dt_emissao) <= 9 THEN 1 ELSE 0 END) flg_u9m,
        (CASE WHEN MONTHS_BETWEEN("{dt_proc_book_str}", dt_emissao) <= 12 THEN 1 ELSE 0 END) flg_u12m
    FROM
        stage
""")
janelas_tempo.createOrReplaceTempView('janelas_tempo')

print('Amostra da tabela janelas_tempo (stage + flags de 1, 3, 6, 9 e 12 meses):')
janelas_tempo.show(5)

# Criação do book de variáveis
fbcs = ['PAGAMENTO_NO_PRAZO','PAGAMENTO_ANTECIPADO','SEM_PAGAMENTO','PAGAMENTO_EM_ATRASO']
fbcs_vlr = ['VALOR_TOTAL','VALOR_PARCIAL','SEM_VALOR']
fvls = ['FVL_VLR_FATURA','FVL_QTD_TRANSACAO','FVL_NUMERO_DIAS_ATRASO','FVL_PERC_VLR_FATURA']
janelas = ['1','FLG_U1M','FLG_U3M','FLG_U6M','FLG_U9M','FLG_U12M']
aggs = ['SUM','AVG','MIN','MAX']
count = 1

for fbc in fbcs:
  for fvl in fvls:
    for janela in janelas:
      for agg in aggs:
        if (fvl == 'FVL_NUMERO_DIAS_ATRASO' and agg == 'SUM') or (fvl == 'FVL_QTD_TRANSACAO' and agg != 'SUM') or (fvl == 'FVL_PERC_VLR_FATURA' and agg == 'SUM'):
          continue
        else:
          print(f'{agg}(CASE WHEN FBC_CLASSIF_PAGTO = "{fbc}" AND {janela} = 1 THEN {fvl} END) as VAR_{count},')
          count += 1

for fbc_vlr in fbcs_vlr:
  for fvl in fvls:
    for janela in janelas:
      for agg in aggs:
        if (fvl == 'FVL_NUMERO_DIAS_ATRASO' and agg == 'SUM') or (fvl == 'FVL_QTD_TRANSACAO' and agg != 'SUM') or (fvl == 'FVL_PERC_VLR_FATURA' and agg == 'SUM'):
          continue
        else:
          print(f'{agg}(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "{fbc_vlr}" AND {janela} = 1 THEN {fvl} END) as VAR_{count},')
          count += 1

book = spark.sql("""
SELECT
id_cliente,
ref,
dt_proc,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_1,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_2,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_3,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_4,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_5,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_6,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_7,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_8,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_9,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_10,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_11,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_12,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_13,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_14,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_15,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_16,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_17,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_18,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_19,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_20,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_21,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_22,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_23,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_24,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_QTD_TRANSACAO END) as VAR_25,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_26,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_27,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_28,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_29,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_30,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_31,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_32,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_33,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_34,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_35,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_36,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_37,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_38,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_39,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_40,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_41,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_42,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_43,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_44,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_45,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_46,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_47,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_48,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_49,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_50,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_51,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_52,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_53,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_54,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_55,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_56,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_57,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_58,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_59,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_60,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_61,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_62,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_63,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_64,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_65,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_NO_PRAZO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_66,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_67,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_68,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_69,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_70,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_71,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_72,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_73,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_74,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_75,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_76,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_77,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_78,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_79,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_80,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_81,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_82,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_83,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_84,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_85,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_86,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_87,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_88,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_89,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_90,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_QTD_TRANSACAO END) as VAR_91,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_92,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_93,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_94,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_95,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_96,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_97,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_98,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_99,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_100,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_101,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_102,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_103,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_104,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_105,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_106,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_107,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_108,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_109,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_110,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_111,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_112,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_113,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_114,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_115,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_116,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_117,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_118,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_119,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_120,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_121,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_122,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_123,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_124,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_125,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_126,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_127,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_128,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_129,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_130,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_131,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_ANTECIPADO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_132,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_133,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_134,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_135,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_136,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_137,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_138,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_139,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_140,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_141,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_142,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_143,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_144,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_145,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_146,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_147,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_148,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_149,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_150,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_151,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_152,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_153,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_154,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_155,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_156,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_QTD_TRANSACAO END) as VAR_157,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_158,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_159,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_160,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_161,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_162,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_163,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_164,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_165,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_166,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_167,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_168,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_169,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_170,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_171,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_172,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_173,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_174,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_175,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_176,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_177,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_178,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_179,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_180,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_181,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_182,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_183,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_184,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_185,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_186,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_187,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_188,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_189,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_190,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_191,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_192,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_193,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_194,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_195,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_196,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_197,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "SEM_PAGAMENTO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_198,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_199,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_200,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_201,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_202,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_203,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_204,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_205,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_206,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_207,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_208,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_209,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_210,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_211,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_212,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_213,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_214,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_215,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_216,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_217,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_218,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_219,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_220,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_221,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_222,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_QTD_TRANSACAO END) as VAR_223,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_224,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_225,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_226,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_227,
SUM(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_228,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_229,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_230,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_231,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_232,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_233,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_234,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_235,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_236,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_237,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_238,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_239,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_240,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_241,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_242,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_243,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_244,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_245,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_246,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_247,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_248,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_249,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_250,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_251,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_252,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_253,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_254,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_255,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_256,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_257,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_258,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_259,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_260,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_261,
AVG(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_262,
MIN(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_263,
MAX(CASE WHEN FBC_CLASSIF_PAGTO = "PAGAMENTO_EM_ATRASO" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_264,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_265,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_266,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_267,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_268,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_269,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_270,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_271,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_272,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_273,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_274,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_275,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_276,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_277,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_278,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_279,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_280,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_281,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_282,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_283,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_284,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_285,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_286,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_287,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_288,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_QTD_TRANSACAO END) as VAR_289,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_290,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_291,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_292,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_293,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_294,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_295,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_296,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_297,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_298,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_299,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_300,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_301,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_302,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_303,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_304,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_305,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_306,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_307,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_308,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_309,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_310,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_311,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_312,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_313,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_314,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_315,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_316,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_317,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_318,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_319,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_320,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_321,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_322,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_323,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_324,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_325,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_326,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_327,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_328,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_329,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_TOTAL" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_330,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_331,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_332,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_333,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_334,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_335,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_336,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_337,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_338,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_339,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_340,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_341,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_342,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_343,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_344,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_345,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_346,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_347,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_348,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_349,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_350,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_351,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_352,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_353,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_354,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_QTD_TRANSACAO END) as VAR_355,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_356,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_357,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_358,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_359,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_360,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_361,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_362,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_363,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_364,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_365,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_366,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_367,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_368,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_369,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_370,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_371,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_372,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_373,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_374,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_375,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_376,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_377,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_378,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_379,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_380,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_381,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_382,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_383,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_384,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_385,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_386,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_387,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_388,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_389,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_390,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_391,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_392,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_393,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_394,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_395,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_396,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_397,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_398,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_399,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_VLR_FATURA END) as VAR_400,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_401,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_402,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_403,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_VLR_FATURA END) as VAR_404,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_405,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_406,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_407,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_VLR_FATURA END) as VAR_408,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_409,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_410,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_411,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_VLR_FATURA END) as VAR_412,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_413,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_414,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_415,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_VLR_FATURA END) as VAR_416,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_417,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_418,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_419,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_VLR_FATURA END) as VAR_420,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_QTD_TRANSACAO END) as VAR_421,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_422,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_423,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_424,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_425,
SUM(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_QTD_TRANSACAO END) as VAR_426,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_427,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_428,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_429,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_430,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_431,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_432,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_433,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_434,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_435,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_436,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_437,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_438,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_439,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_440,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_441,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_442,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_443,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_NUMERO_DIAS_ATRASO END) as VAR_444,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_445,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_446,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND 1 = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_447,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_448,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_449,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U1M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_450,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_451,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_452,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U3M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_453,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_454,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_455,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_456,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_457,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_458,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U9M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_459,
AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_460,
MIN(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_461,
MAX(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "SEM_VALOR" AND FLG_U12M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_462
FROM
janelas_tempo
GROUP BY
id_cliente, ref, dt_proc
""")

book.createOrReplaceTempView('book')

print('Amostra book:')
book.show(5)

book.where('id_cliente == 345').show()

"""VAR_388 = 50.5000

AVG(CASE WHEN FBC_CLASSIF_VLR_PAGTO = "VALOR_PARCIAL" AND FLG_U6M = 1 THEN FVL_PERC_VLR_FATURA END) as VAR_388
"""
# Salavamento do Book na camada Refined
book.write.partitionBy('ref','dt_proc').parquet(f"s3://lake-project-/0003_refined/book_fatura/", mode='append')

